general.import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

# Alacritty can automatically reload the configuration file when the file is changed
general.live_config_reload = true

# The `TERM` variable is put under the `env` key which sets environment variables that are passed to the shell when Alacritty is launched
[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless" # Removes the macOS title bar and border
dynamic_padding = true
opacity = 0.97 # Takes a value between `0-1` and makes the window semi-transparent

[window.padding]
x = 15
y = 17

[font]
size = 12.0

[font.normal]
family = "Monaco"
style = "Regular"

[font.italic]
family = "Menlo"
style = "Italic"

[font.bold]
family = "Menlo"
style = "Bold"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
