# --- Clipboard and Terminal Fixes ---
# Use the system clipboard
set -g set-clipboard on

# Tell tmux that Alacritty supportts clipboard escpae sequences (OSC52)
# If 'alacritty' doesn't work, try 'xterm-256color' here
set -as terminal-features ',xterm-256color:clipboard'
set -as terminal-overrides ',xterm-256color:Ms=\E]52;c;%p2%s\7'

# Fix ESC delay for Neovim
set -s escape-time 0

# Enable focus events (help Neovim know when you switch panes)
set -g focus-events on

# --- Pane Management ---
# Balance panes horizontally
bind-key = select-layout even-horizontal

# Balance panes vertically
bind-key + select-layout event-vertical

# Tiled layout
bind-key | select-layout tiled

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- Session/Pane killing ---
# Kill session
bind U confirm-before -p "Kill session #S? (y/n)" kill-session

# Kill current pane
bind u confirm-before -p "Kill this pane? (y/n)" kill-pane

